pipeline:
  name: sample-pipeline-inline
  identifier: samplepipelineinline
  projectIdentifier: Lab_shankar
  orgIdentifier: tpmtraining
  tags: {}
  stages:
    - stage:
        name: deploy-dev
        identifier: deploy
        description: "hi this is prasad satam"
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: samplewebapp
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devnamespace
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+pipeline.stages.deploy.spec.serviceVariables.replica>
                          echo "<+pipeline.variables.InputVar1> was the input"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: Verify
                  name: Verify_1
                  identifier: Verify_1
                  spec:
                    isMultiServicesOrEnvs: false
                    type: Rolling
                    monitoredService:
                      type: Default
                      spec: {}
                    spec:
                      sensitivity: HIGH
                      duration: 10m
                  timeout: 2h
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Verification
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: StageRollback
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 2h
                            onTimeout:
                              action:
                                type: Ignore
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: deploy-prod
        identifier: deployprod
        tags: {}
        template:
          templateRef: Proddeploytemplate
          versionLabel: V1
  variables:
    - name: InputVar1
      type: String
      description: ""
      required: false
      value: <+input>
